---
- name: print to stdout
  command: "ls -la /vagrant/ansible/files/www/Dockerfile"
  register: result

- debug: msg="{{ result.stdout }}"


- name: Build Docker images from Dockerfiles.
  docker_image:
    name: nginx
    tag: neil
    path: "/vagrant/ansible/files/www/"
    state: build

- name: run the site in a docker container
  docker:
    name: site1
    image: "nginx:neil"
    state: reloaded
    ports:
      - "18080:80"